service: serverless-url-shortner-with-lambda

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:PutItem
        - dynamodb:GetItem
      Resource: arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.dbTableName}

custom:
  dbTableName: url-shortner-table

functions:
  addShortUrl:
    handler: url_shortner_handlers/add_short_url.handler
    environment:
      ddbName: ${self:custom.dbTableName}
    events:
      - http:
          path: /url-shortner/add
          method: post

  getShortUrl:
    handler: url_shortner_handlers/get_short_url.handler
    environment:
      ddbName: ${self:custom.dbTableName}
    events:
      - http:
          path: /url-shortner/get/{id}
          method: get      

# you can add CloudFormation resource templates here
resources:
 Resources:
   urlShortnerTable:
     Type: AWS::DynamoDB::Table
     Properties:
        TableName: ${self:custom.dbTableName}
        AttributeDefinitions:
          - AttributeName: short_url
            AttributeType: S
        BillingMode: PROVISIONED
        KeySchema:
          - AttributeName: short_url
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5    


